1. Implement a program to insert an element at a specific position in a list.
---

In [5]:
l=[10,20,30]
#input element and position
element=int(input('Enter the element to be inserted'))
pos=int(input('Enter the position (0-n)'))
#Inserting the element to the list
l.insert(pos,element)
#Displaying the updated list
print(l)

Enter the element to be inserted 5
Enter the position (0-n) 2


[10, 20, 5, 30]


2. Find the maximum and minimum elements in a list without using max() or min().
---

In [10]:
numbers=[10,20,30,40]
maximum=numbers[0]
minimum=numbers[0]
for i in numbers:
    if i>maximum:
        maximum=i
    if i<minimum:
        minimum=i
print('MAX value:',maximum)
print('MIN value:',minimum)

MAX value: 40
MIN value: 10


3. Remove all negative numbers from a list.
---

In [16]:
integers=[-5,-4,-3,-2,-1,0,1,2,3,4,5]
#Sorting out non-negative no using list comprehension
pos_no=[i for i in integers if i>=0]
print(' Original List',integers,'\n','List with non-negative integers',pos_no)

 Original List [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5] 
 List with non-negative integers [0, 1, 2, 3, 4, 5]


4. Reverse a list using slicing and a loop.
---

In [22]:
numbers = [10, 20, 30, 40, 50]

#Using slicing
rlist_slicing=numbers[::-1]
print('Reversed list  using slicing',rlist_slicing)

#Using loop
rlist_loop=[]
x=len(numbers)
for i in range(x-1,-1,-1):
    rlist_loop.append(numbers[i])
print('Reversed list using loop    ',rlist_loop)

Reversed list  using slicing [50, 40, 30, 20, 10]
Reversed list using loop     [50, 40, 30, 20, 10]


5. Merge two sorted lists into a single sorted list.
---

In [25]:
L1=[1,3,5,7]
L2=[2,4,6,8,10]
sorted_list=sorted(L1+L2)
print('Merged sorted list:',sorted_list)

Merged sorted list: [1, 2, 3, 4, 5, 6, 7, 8, 10]


6. Convert a list into a tuple and vice versa.
---

In [28]:
#Convert a list into tuple
lt_list=[10,20,30,40]
lt_tuple=tuple(lt_list)
print('List:',lt_list)
print('Converted list:',lt_tuple)
print()

#Convert a tuple to list 
tl_tuple=(10, 20, 30, 40)
tl_list=list(tl_tuple)
print('Tuple:',tl_tuple)
print('Converted List:',tl_list)

List: [10, 20, 30, 40]
Converted list: (10, 20, 30, 40)

Tuple: (10, 20, 30, 40)
Converted List: [10, 20, 30, 40]


7. Find the common elements in two sets.
---

In [31]:
set1={1, 2, 3, 4, 5}
set2={4, 5, 6, 7, 8}
common=set1&set2 #Using intersection operator &
print('Common elements:',common)

Common elements: {4, 5}


8. Write a program to remove duplicate elements from a list using a set.
---

In [33]:
my_list=[10, 20, 30, 20, 40, 10, 50, 30]
unique=list(set(my_list)) #Convert to set (removes duplicates), then back to list
print('List after removing duplicates:',unique)

List after removing duplicates: [40, 10, 50, 20, 30]


9. Check if two sets are disjoint.
---

In [40]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
set3 = {3, 6, 9}
print("Set1 and Set2 disjoint? =>",set1.isdisjoint(set2)) 
print("Set1 and Set3 disjoint? =>",set1.isdisjoint(set3))
print("Set2 and Set3 disjoint? =>",set2.isdisjoint(set3))  

Set1 and Set2 disjoint? => True
Set1 and Set3 disjoint? => False
Set2 and Set3 disjoint? => False


10. Create a set from user input and check membership of an element.
---

In [53]:
#Taking input from user (space-seperated values)
user_input=set(input('Enter the set (just enter with a single space):').split())
print('Created set:',user_input)
#Checking membership
element=input('Enter an element to check')
if element in user_input:
    print(element,'is present in the set')
else:
    print(element,'is not present in the set')

Enter the set (just enter with a single space): 1 2 3 4 5 6


Created set: {'2', '3', '1', '6', '5', '4'}


Enter an element to check 10


10 is not present in the set


11. Count the frequency of each character in a string using a dictionary.
---

In [57]:
text=input('Enter a string:')
freq={}
for char in text:
    if char in freq:
        freq[char]+=1
    else:
        freq[char]=1
print('Character frequencies:')
for k,v in freq.items():
    print(k,':',v)

Enter a string: hello


Character frequencies:
h : 1
e : 1
l : 2
o : 1


12. Create a dictionary from two lists: one of keys and one of values.
---

In [68]:
keys=["name","age","city"]
values=["Sam",25,"Alberquerque"]
my_dict={keys[i]:values[i] for i in range(len(keys))}
print('Dictionary:',my_dict)

Dictionary: {'name': 'Sam', 'age': 25, 'city': 'Alberquerque'}


13. Write a program to sort a dictionary by its values.
---

In [77]:
fruits={'apple':5,'banana':2,'mango':8,'orange':3}
sorted_items=sorted(fruits.items(),key=lambda x:x[1])
print('Sorted dictionary:',dict(sorted_items))

Sorted dictionary: {'banana': 2, 'orange': 3, 'apple': 5, 'mango': 8}


14. Merge two dictionaries into one.
---

In [84]:
dict1={'a':1,'b':2}
dict2={'c':3,'d':4}
dict1.update(dict2)
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

15. Find the key with the highest value in a dictionary.
---

In [94]:
veggies={"carrot":25,"potato":40,"tomato":35,"onion":50}
max_=max(veggies,key=veggies.get)
print('Vegetable with highest value:',max_)
print('Its value is:',veggies[max_])

Vegetable with highest value: onion
Its value is: 50


16. Write a function that checks if a number is prime.
---

In [97]:
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,n):
        if n%i==0:
            return False
    return True

# Input from user
num = int(input("Enter a number: "))
if is_prime(num):
    print(num, "is a prime number.")
else:
    print(num, "is not a prime number.")

Enter a number:  1


1 is not a prime number.


17. Create a function that takes a string and returns the number of vowels.
---


In [98]:
v=['a','e','i','o','u','A','E','I','O','U']
vc=0
s=input('Enter a string:')
for i in s:
    if i in v:
        vc+=1
print(vc)

Enter a string: Hello World 


3


18. Write a function that takes a list of numbers and returns only the even numbers.
---

In [100]:
List=[1,2,3,4,5,6,7,8,9,10]
eve=[n for n in List if n%2==0]
print('The list of even numbers are:',eve)

The list of even numbers are: [2, 4, 6, 8, 10]


19. Write a recursive function to calculate the factorial of a number.
---

In [101]:
def factorial(num):
    f=1
    if num==0:
        return f'The factorial of {num} is',f
    elif num<1:
       return 'Undefined for NEGATIVE number'
    else:
        for i in range(1,num+1):
            f=f*i
    return f'The factorial of {num} is',f
num=int(input("Enter a Number"))
factorial(num)

Enter a Number 5


('The factorial of 5 is', 120)

20. Write a function that returns the nth Fibonacci number using recursion.
---

In [105]:
def fibonacci(n):
    if n==0 or n==1:  
        return n
    return fibonacci(n-1)+fibonacci(n-2)  # Calls itself
n = int(input("Enter which Fibonacci number to find: "))
print(f"The {n}th Fibonacci number is {fibonacci(n)}")

Enter which Fibonacci number to find:  10


The 10th Fibonacci number is 55


21. Write a function that takes a list and returns a dictionary with the count of each element.
---

In [108]:
def count_elements(lst):
    count_dict = {}  
    for i in lst:
        if i in count_dict:
            count_dict[i] += 1
        else:
            count_dict[i] = 1
    return count_dict
my_list = ["apple", "banana", "apple", "orange", "banana", "apple"]
result = count_elements(my_list)
print(result)

{'apple': 3, 'banana': 2, 'orange': 1}


22. Create a function that returns the longest word from a list of words.
---

In [110]:
def longest_word(words):
    if not words: 
        return None
    longest = words[0]  
    for word in words:
        if len(word) > len(longest):
            longest = word
    return longest
word_list = ["apple", "banana", "cherry", "watermelon", "kiwi"]
print("The longest word is:", longest_word(word_list))

The longest word is: watermelon


23. Define a function that accepts any number of arguments and returns their average.
---

In [119]:
def average(*args):
    if not args:  
        return 0
    total = sum(args)
    count = len(args)
    return total/count
n=input('Enter the numbers to find the avg (single space for muli entries):')
numbers=[int(x) for x in n.split()]
print('Average:',average(*numbers))

Enter the numbers to find the avg (single space for muli entries): 1 2 3


Average: 2.0


24. Write a function with default arguments for user name and age, and print a greeting.
---

In [124]:
def greet(name="Guest", age=18):
    print(f"Hello {name}! You are {age} years old.")
greet()                       
greet("Walter")            
greet("Walter", 17)        


Hello Guest! You are 18 years old.
Hello Walter! You are 18 years old.
Hello Walter! You are 17 years old.


25. Use a lambda function to sort a list of tuples by the second element.
---


In [125]:
my_list = [(1, 5), (2, 2), (3, 9), (4, 1)]
sorted_list = sorted(my_list, key=lambda x: x[1])
print("Sorted list:", sorted_list)

Sorted list: [(4, 1), (2, 2), (1, 5), (3, 9)]


26. Write a function that accepts a list of numbers and a condition function, and returns a filtered list.
---

In [126]:
def filter_list(numbers, condition):
    filtered = []
    for num in numbers:
        if condition(num):
            filtered.append(num)
    return filtered
def is_even(n):
    return n % 2 == 0
nums = [1, 2, 3, 4, 5, 6]
result = filter_list(nums, is_even)
print("Filtered list (even numbers):", result)

Filtered list (even numbers): [2, 4, 6]


27. Create a function to check whether a string is a palindrome or not.
---

In [127]:
def palindrome(x):
    if x==x[::-1]:
        print('The given word is PALINDROME')
    else:
        print('The given word is not PALINDROME')
word=input('Enter a word:')
w=word.lower()
palindrome(w)

Enter a word: mom


The given word is PALINDROME


28. Write a function to return the GCD of two numbers.
---

In [128]:
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("GCD is", gcd(num1, num2))

Enter first number:  24
Enter second number:  36


GCD is 12


29. Define a function that returns another function (closure) that adds a fixed number to its input.
---

In [143]:
def add_fixed_number(fixed):
    def adder(x):
        return x+fixed
    return adder
add5=add_fixed_number(5)
print(add5(10))  
print(add5(3))

15
8


30. Write a function to flatten a nested list (e.g., [[1,2],[3,4]] → [1,2,3,4]).
---

In [144]:
def flatten_list(nested_list):
    flat_list = []
    for sublist in nested_list:
        for item in sublist:
            flat_list.append(item)
    return flat_list
nums = [[1, 2], [3, 4]]
print("Flattened list:", flatten_list(nums))

Flattened list: [1, 2, 3, 4]


31. Write a recursive function to calculate the sum of a list.
---

In [145]:
def sum_list(lst):
    if not lst:  
        return 0
    else:
        return lst[0] + sum_list(lst[1:])  
numbers = [1, 2, 3, 4, 5]
print("Sum of list:", sum_list(numbers))

Sum of list: 15


32. Define a function that takes two lists and returns a dictionary mapping elements of the first list to the second.
---

In [146]:
def lists_to_dict(keys, values):
    return dict(zip(keys, values))
names = ["apple", "banana", "cherry"]
prices = [100, 40, 60]
print(lists_to_dict(names, prices))

{'apple': 100, 'banana': 40, 'cherry': 60}


33. Create a function to return all prime numbers in a given range.
---

In [148]:
def primes_in_range(start, end):
    for num in range(start, end + 1):
        if num > 1:
            for i in range(2, num):
                if num % i == 0:
                    break
            else:
                print(num)
primes_in_range(10, 30)

11
13
17
19
23
29


34. Write a function that mimics the zip() function.
---

In [152]:
def my_zip(a, b):
    result = []
    for i in range(len(a)):
        result.append((a[i], b[i]))
    return result
print(my_zip([1, 2, 3], ['a', 'b', 'c']))

[(1, 'a'), (2, 'b'), (3, 'c')]


35. Create a function that calculates compound interest given principal, rate, and time.
---

In [154]:
def compound_interest(principal, rate, time):
    # CI formula: A = P * (1 + r/100)^t
    amount = principal * (1 + rate/100) ** time
    ci = amount - principal
    return ci
p = float(input("Enter principal amount: "))
r = float(input("Enter rate of interest (%): "))
t = float(input("Enter time in years: "))
print("Compound Interest:", compound_interest(p, r, t))

Enter principal amount:  1000
Enter rate of interest (%):  5
Enter time in years:  2


Compound Interest: 102.5


36. Use a lambda function to add 10 to a given number.
---

In [157]:
add_10 = lambda x:x+10
print(add_10(5))   
print(add_10(20))  

15
30


37. Sort a list of tuples based on the second element using a lambda function.
---

In [160]:
my_list=[(1,5),(2,2),(3,9),(4,1)]
sorted_list=sorted(my_list,key=lambda x:x[1])
print("Sorted list:",sorted_list)

Sorted list: [(4, 1), (2, 2), (1, 5), (3, 9)]


38. Sort a list of dictionaries by the value of a specific key using lambda.
---

In [162]:
# List of dictionaries
students = [
    {"name": "Alice", "age": 25},
    {"name": "Bob", "age": 22},
    {"name": "Charlie", "age": 23}
]
#Sort by age
sorted_students = sorted(students, key=lambda x: x["age"])
print("Sorted list:", sorted_students)

Sorted list: [{'name': 'Bob', 'age': 22}, {'name': 'Charlie', 'age': 23}, {'name': 'Alice', 'age': 25}]


39. Use lambda with map() to square each element in a list.
---

In [165]:
# Original list
numbers = [1, 2, 3, 4, 5]
# Use lambda with map to square each element
squared = list(map(lambda x: x**2, numbers))
print("Squared list:", squared)

Squared list: [1, 4, 9, 16, 25]


40. Use lambda with filter() to get only the even numbers from a list.
---

In [168]:
# Original list
numbers=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Use lambda with filter to get even numbers
even_numbers=list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)

Even numbers: [2, 4, 6, 8, 10]


41. Use lambda with reduce() to multiply all elements in a list.
---

In [173]:
from functools import reduce  # reduce is in functools module
# Original list
numbers = [1, 2, 3, 4, 5]
# Use lambda with reduce to multiply all elements
result = reduce(lambda x, y: x * y, numbers)
print("Product of all elements:", result)

Product of all elements: 120


42. Create a lambda function to check if a number is divisible by both 3 and 5.
---

In [172]:
# Lambda function to check divisibility by both 3 and 5
divisible = lambda x: x % 3 == 0 and x % 5 == 0
print(divisible(15))  
print(divisible(10))  
print(divisible(30))  

True
False
True


43. Use lambda with map() to convert a list of temperatures from Celsius to Fahrenheit.
---

In [175]:
# List of temperatures in Celsius
celsius = [0, 20, 37, 100]
# Convert to Fahrenheit using lambda and map
fahrenheit = list(map(lambda c: (c * 9/5) + 32, celsius))
print("Temperatures in Fahrenheit:", fahrenheit)

Temperatures in Fahrenheit: [32.0, 68.0, 98.6, 212.0]


44. Use lambda to sort a list of strings based on their length.
---

In [176]:
# List of strings
words = ["apple", "kiwi", "banana", "cherry", "fig"]
# Sort by string length
sorted_words = sorted(words, key=lambda x: len(x))
print("Sorted by length:", sorted_words)

Sorted by length: ['fig', 'kiwi', 'apple', 'banana', 'cherry']


45. Write a lambda that returns True if a string starts with a vowel.
---

In [180]:
# Lambda to check if a string starts with a vowel
starts_with_vowel = lambda s: s[0].lower() in 'aeiou'
print(starts_with_vowel("Apple"))   
print(starts_with_vowel("banana"))   
print(starts_with_vowel("Orange"))  

True
False
True


46. Use lambda inside a function that returns a power function (closure).
---

In [181]:
def make_power(n):
    return lambda x: x ** n   
square = make_power(2)
cube = make_power(3)
print(square(5))  
print(cube(2))    

25
8


47. Write a lambda to extract domain names from a list of email addresses.
---

In [182]:
# List of email addresses
emails = ["alice@gmail.com", "bob@yahoo.com", "charlie@outlook.com"]
# Lambda with map to extract domains
domains = list(map(lambda email: email.split('@')[1], emails))
print("Domain names:", domains)

Domain names: ['gmail.com', 'yahoo.com', 'outlook.com']


48. Use lambda with filter() to remove empty strings from a list.
---

In [183]:
# List with empty strings
words = ["apple", "", "banana", " ", "cherry", ""]
# Use lambda with filter to remove empty strings
cleaned = list(filter(lambda x: x.strip() != "", words))
print("After removing empty strings:", cleaned)

After removing empty strings: ['apple', 'banana', 'cherry']


49. Create a list of lambda functions, each returning a different multiple of 5 (e.g., 5, 10, 15,...).
---

In [184]:
# Create list of lambda functions
multiples = [lambda x=n: x * 5 for n in range(1, 6)]
# Example usage — call each function
for func in multiples:
    print(func())

5
10
15
20
25


50. Use a lambda to find the maximum element in a list of tuples by sum of tuple elements.
---

In [185]:
# List of tuples
tuples_list = [(1, 2), (3, 4), (5, 1), (2, 8)]
# Find the tuple with maximum sum
max_tuple = max(tuples_list, key=lambda x: sum(x))
print("Tuple with maximum sum:", max_tuple)

Tuple with maximum sum: (2, 8)


51. Use lambda and map() to convert a list of integers to strings.
---

In [186]:
# List of integers
numbers = [1, 2, 3, 4, 5]
# Convert to strings using lambda and map
str_numbers = list(map(lambda x: str(x), numbers))
print("List of strings:", str_numbers)

List of strings: ['1', '2', '3', '4', '5']


52. Use lambda with filter() to extract palindromic words from a list.
---

In [187]:
# List of words
words = ["level", "apple", "radar", "banana", "civic", "hello"]
# Use lambda with filter to get palindromes
palindromes = list(filter(lambda w: w == w[::-1], words))
print("Palindromic words:", palindromes)

Palindromic words: ['level', 'radar', 'civic']


53. Use lambda with sorted() to sort a list of strings by their last character.
---

In [188]:
# List of strings
words = ["apple", "banana", "cherry", "date"]
# Sort by last character
sorted_words = sorted(words, key=lambda x: x[-1])
print("Sorted by last character:", sorted_words)

Sorted by last character: ['banana', 'apple', 'date', 'cherry']


54. Combine lambda, map(), and zip() to add two lists element-wise.
---

In [189]:
# Two lists
list1 = [1, 2, 3, 4]
list2 = [10, 20, 30, 40]
# Add element-wise using lambda, map, and zip
sum_list = list(map(lambda x: x[0] + x[1], zip(list1, list2)))
print("Element-wise sum:", sum_list)

Element-wise sum: [11, 22, 33, 44]


55. Use lambda to count how many strings in a list have length > 5.
---

In [192]:
# List of strings
words = ["apple", "banana", "cherry", "fig", "watermelon"]
# Count strings with length > 5 using lambda and filter
count = len(list(filter(lambda x: len(x) > 5, words)))
print("Number of strings with length > 5:", count)

Number of strings with length > 5: 3


56. Write a program to create a text file and write "Hello, World!" into it.
---

In [193]:
# Open a file in write mode 
with open("hello.txt", "w") as file:
    file.write("Hello, World!")
print("Text file created and message written successfully.")

Text file created and message written successfully.


57. Write a program to read the contents of a file and print them line by line.
---

In [194]:
# Open the file in read mode
with open("hello.txt", "r") as file:
    # Read and print each line
    for line in file:
        print(line.strip())  # strip() removes the newline character

Hello, World!


58. Append a new line to an existing file without overwriting its contents.
---

In [196]:
# Open the file in append mode
with open("hello.txt", "a") as file:
    file.write("\nThis is a new line.")
print("New line appended successfully.")

New line appended successfully.


59. Count the number of words in a given file.
---

In [197]:
# Open the file in read mode
with open("hello.txt", "r") as file:
    content = file.read()           # Read the entire file
    words = content.split()         # Split by whitespace to get words
    word_count = len(words)         # Count the number of words
print("Number of words in the file:", word_count)

Number of words in the file: 12


60. Copy the contents of one file to another.
---

In [199]:
with open("source.txt", "w") as f:
    f.write("Hello World.\n")
# Open the source file in read mode and destination file in write mode
with open("source.txt", "r") as src, open("destination.txt", "w") as dest:
    for line in src:
        dest.write(line)
print("Contents copied successfully.")

Contents copied successfully.


61. Write a program to read a file and count how many lines it has.
---

In [200]:
# Open the file in read mode
with open("hello.txt", "r") as file:
    line_count = sum(1 for line in file)  # Count lines
print("Number of lines in the file:", line_count)

Number of lines in the file: 3


62. Write a program to read a file and display only the lines that contain the word "Python".
---

In [206]:
# Create sample file
with open("hello.txt", "w") as f:
    f.write("Hello, World!\nWelcome to Python.\nPython is fun!\nI love coding.")
# Read lines containing 'Python'
with open("hello.txt", "r") as file:
    for line in file:
        if "Python" in line:
            print(line.strip())

Welcome to Python.
Python is fun!


63. Create a function that takes a filename and returns the number of characters in that file.
---

In [207]:
def count_characters(filename):
    try:
        with open(filename, "r") as file:
            content = file.read()        # Read the entire file
            return len(content)          # Count characters
    except FileNotFoundError:
        print("File not found!")
        return 0
filename = "hello.txt"
print(f"Number of characters in {filename}:", count_characters(filename))

Number of characters in hello.txt: 62


64. Write a program that divides two numbers and handles ZeroDivisionError.
---

In [208]:
# Take input from the user
num1 = float(input("Enter the numerator: "))
num2 = float(input("Enter the denominator: "))
try:
    result = num1 / num2
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

Enter the numerator:  6
Enter the denominator:  3


Result: 2.0


65. Read a number from the user and raise a ValueError if it's negative.
---

In [210]:
# Read a number from the user
num = float(input("Enter a number: "))
# Check if the number is negative
if num < 0:
    raise ValueError("Error: Negative numbers are not allowed!")
print("You entered:", num)

Enter a number:  -5


ValueError: Error: Negative numbers are not allowed!

66. Write a program to open a file that may not exist and handle FileNotFoundError.
---

In [211]:
filename = "example.txt"
try:
    with open(filename, "r") as file:
        content = file.read()
        print("File contents:")
        print(content)
except FileNotFoundError:
    print(f"Error: The file '{filename}' does not exist!")

Error: The file 'example.txt' does not exist!


67. Create a function that handles both ValueError and TypeError while taking input.
---

In [212]:
def get_number():
    try:
        num = int(input("Enter an integer: "))
        return num
    except ValueError:
        print("Error: Invalid input! Please enter a valid integer.")
    except TypeError:
        print("Error: Type mismatch occurred!")
number = get_number()
print("You entered:", number)

Enter an integer:  a


Error: Invalid input! Please enter a valid integer.
You entered: None


68. Use a try...except...finally block to handle exceptions and close a file properly.
---

In [213]:
filename = "example.txt"
file = None
try:
    file = open(filename, "r")  # Attempt to open the file
    content = file.read()
    print("File contents:")
    print(content)
except FileNotFoundError:
    print(f"Error: The file '{filename}' does not exist!")
except Exception as e:
    print("An unexpected error occurred:", e)
finally:
    if file:
        file.close()  # Ensure the file is closed
        print("File has been closed.")

Error: The file 'example.txt' does not exist!


69. Write a program that attempts to convert user input to an integer and handles invalid input.
---

In [215]:
try:
    num = int(input("Enter a number: "))
    print("You entered:", num)
except ValueError:
    print("Error: Invalid input! Please enter a valid integer.")

Enter a number:  123.3


Error: Invalid input! Please enter a valid integer.


70. Use try...except to read from a file and display a custom error message if the file cannot be read.
---

In [217]:
filename = "example.txt"
try:
    with open(filename, "r") as file:
        content = file.read()
        print("File contents:")
        print(content)
except (FileNotFoundError, IOError):
    print(f"Error: Cannot read the file '{filename}'. Please check if it exists and is accessible.")

Error: Cannot read the file 'example.txt'. Please check if it exists and is accessible.


71. Create a 4x4 NumPy array filled with random integers from 10 to 50. Replace all odd numbers with -1.
---

In [219]:
import numpy as np
# Create a 4x4 array of random integers from 10 to 50
arr = np.random.randint(10, 51, size=(4, 4))
print("Original array:\n", arr)
# Replace odd numbers with -1
arr[arr % 2 == 1] = -1
print("\nArray after replacing odd numbers with -1:\n", arr)

Original array:
 [[26 48 49 44]
 [38 14 35 48]
 [39 13 17 39]
 [38 50 39 32]]

Array after replacing odd numbers with -1:
 [[26 48 -1 44]
 [38 14 -1 48]
 [-1 -1 -1 -1]
 [38 50 -1 32]]


72. Given a 1D NumPy array, write a program to compute the difference between each element and the mean of the array.
---

In [221]:
# Example 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
# Compute the mean
mean_val = np.mean(arr)
print("Mean of the array:", mean_val)
# Compute difference between each element and the mean
diff = arr - mean_val
print("Difference from mean:", diff)

Original array: [10 20 30 40 50]
Mean of the array: 30.0
Difference from mean: [-20. -10.   0.  10.  20.]


73. Create a 5x5 identity matrix and change the diagonal values to a custom value (e.g., 9).
----

In [222]:
# Create a 5x5 identity matrix
matrix = np.eye(5)
print("Original identity matrix:\n", matrix)
# Change diagonal values to 9
np.fill_diagonal(matrix, 9)
print("\nMatrix after changing diagonal values to 9:\n", matrix)

Original identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matrix after changing diagonal values to 9:
 [[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]


74. Stack two NumPy arrays of shape (3, 4) vertically and horizontally.
---

In [223]:
# Create two sample arrays of shape (3, 4)
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
arr2 = np.array([[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]])
# Vertical stacking (adds rows)
v_stack = np.vstack((arr1, arr2))
print("Vertically stacked array:\n", v_stack)
# Horizontal stacking (adds columns)
h_stack = np.hstack((arr1, arr2))
print("\nHorizontally stacked array:\n", h_stack)

Vertically stacked array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Horizontally stacked array:
 [[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


75. Extract all rows from a 2D array where the first element is greater than 50.
----

In [224]:
# Example 2D array
arr = np.array([[10, 20, 30],
                [60, 70, 80],
                [45, 55, 65],
                [90, 15, 25]])
# Extract rows where the first element > 50
filtered_rows = arr[arr[:, 0] > 50]
print("Rows with first element > 50:\n", filtered_rows)

Rows with first element > 50:
 [[60 70 80]
 [90 15 25]]


76. Create a 6x6 array and extract a 3x3 block from the center of it.
----

In [225]:
# Create a 6x6 array with numbers from 1 to 36
arr = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 array:\n", arr)
# Extract the center 3x3 block
center_block = arr[1:4, 1:4]  # Rows 1-3, Columns 1-3
print("\nCenter 3x3 block:\n", center_block)

Original 6x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Center 3x3 block:
 [[ 8  9 10]
 [14 15 16]
 [20 21 22]]


77. Normalize a 1D array (i.e., scale the values between 0 and 1).
----

In [226]:
# Example 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
# Normalize the array
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized array:", normalized_arr)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


78. Given a 2D array, replace all elements greater than the average with the average itself.
---

In [228]:
# Example 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("Original array:\n", arr)
# Compute the average of all elements
avg = arr.mean()
print("\nAverage value:", avg)
# Replace elements greater than average with the average
arr[arr > avg] = avg
print("\nArray after replacing elements greater than average:\n", arr)

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Average value: 50.0

Array after replacing elements greater than average:
 [[10 20 30]
 [40 50 50]
 [50 50 50]]


79. Find the indices of the top 3 maximum elements in a 1D array.
----

In [229]:
# Example 1D array
arr = np.array([10, 50, 30, 70, 20, 90, 40])
print("Array:", arr)
# Get indices of the top 3 maximum elements
top3_indices = np.argsort(arr)[-3:][::-1]  # Sort indices, take last 3, reverse
print("Indices of top 3 maximum elements:", top3_indices)
# Optional: print the top 3 elements themselves
print("Top 3 maximum elements:", arr[top3_indices])

Array: [10 50 30 70 20 90 40]
Indices of top 3 maximum elements: [5 3 1]
Top 3 maximum elements: [90 70 50]


80. Given a 3D array of shape (2, 3, 4), calculate the sum across axis 1 and axis 2.
----

In [230]:
# Create a 3D array of shape (2, 3, 4) with numbers from 1 to 24
arr = np.arange(1, 25).reshape(2, 3, 4)
print("Original 3D array:\n", arr)
# Sum across axis 1 (sum over the 3 rows in each 2D block)
sum_axis1 = arr.sum(axis=1)
print("\nSum across axis 1:\n", sum_axis1)
# Sum across axis 2 (sum over the 4 columns in each 2D block)
sum_axis2 = arr.sum(axis=2)
print("\nSum across axis 2:\n", sum_axis2)

Original 3D array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Sum across axis 1:
 [[15 18 21 24]
 [51 54 57 60]]

Sum across axis 2:
 [[10 26 42]
 [58 74 90]]


81. Load a CSV file into a DataFrame and display the top 5 rows.
----

In [235]:
import pandas as pd
# Sample DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 28, 35, 22],
    "Country": ["USA", "UK", "Canada", "Australia", "India"]
}
df = pd.DataFrame(data)
# Save as CSV
df.to_csv("data.csv", index=False)
# Now read it
df_loaded = pd.read_csv("data.csv")
print(df_loaded.head())

      Name  Age    Country
0    Alice   25        USA
1      Bob   30         UK
2  Charlie   28     Canada
3    David   35  Australia
4      Eve   22      India


82. Check for missing values in a DataFrame and count them column-wise.
----

In [236]:
# Example DataFrame with some missing values
data = {
    "Name": ["Alice", "Bob", "Charlie", None, "Eve"],
    "Age": [25, None, 28, 35, 22],
    "Country": ["USA", "UK", None, "Australia", "India"]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Check for missing values and count column-wise
missing_counts = df.isnull().sum()
print("\nMissing values column-wise:\n", missing_counts)

DataFrame:
       Name   Age    Country
0    Alice  25.0        USA
1      Bob   NaN         UK
2  Charlie  28.0       None
3     None  35.0  Australia
4      Eve  22.0      India

Missing values column-wise:
 Name       1
Age        1
Country    1
dtype: int64


83. Drop all rows from a DataFrame that contain any missing values.
----

In [237]:
# Example DataFrame with some missing values
data = {
    "Name": ["Alice", "Bob", "Charlie", None, "Eve"],
    "Age": [25, None, 28, 35, 22],
    "Country": ["USA", "UK", None, "Australia", "India"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Drop rows with any missing values
df_clean = df.dropna()
print("\nDataFrame after dropping rows with missing values:\n", df_clean)

Original DataFrame:
       Name   Age    Country
0    Alice  25.0        USA
1      Bob   NaN         UK
2  Charlie  28.0       None
3     None  35.0  Australia
4      Eve  22.0      India

DataFrame after dropping rows with missing values:
     Name   Age Country
0  Alice  25.0     USA
4    Eve  22.0   India


84. Fill missing values in a specific column with the column's mean.
---

In [238]:
# Example DataFrame with some missing values
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, None, 28, 35, 22],
    "Country": ["USA", "UK", "Canada", "Australia", "India"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Fill missing values in the 'Age' column with the column's mean
df['Age'].fillna(df['Age'].mean(), inplace=True)
print("\nDataFrame after filling missing 'Age' values with mean:\n", df)

Original DataFrame:
       Name   Age    Country
0    Alice  25.0        USA
1      Bob   NaN         UK
2  Charlie  28.0     Canada
3    David  35.0  Australia
4      Eve  22.0      India

DataFrame after filling missing 'Age' values with mean:
       Name   Age    Country
0    Alice  25.0        USA
1      Bob  27.5         UK
2  Charlie  28.0     Canada
3    David  35.0  Australia
4      Eve  22.0      India


C:\Users\Hanith\AppData\Local\Temp\ipykernel_21508\968207685.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)


85. Rename multiple columns in a DataFrame using a dictionary.
---

In [239]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "Country": ["USA", "UK", "Canada"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Rename columns using a dictionary
df.rename(columns={"Name": "Full_Name", "Age": "Years", "Country": "Nation"}, inplace=True)
print("\nDataFrame after renaming columns:\n", df)

Original DataFrame:
       Name  Age Country
0    Alice   25     USA
1      Bob   30      UK
2  Charlie   28  Canada

DataFrame after renaming columns:
   Full_Name  Years  Nation
0     Alice     25     USA
1       Bob     30      UK
2   Charlie     28  Canada


86. Select rows where a column's value is between two values (e.g., between 10 and 20).
---

In [240]:
# Example DataFrame
data = {
    "Item": ["A", "B", "C", "D", "E"],
    "Price": [5, 12, 18, 25, 15]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Select rows where 'Price' is between 10 and 20 (inclusive)
filtered_df = df[(df['Price'] >= 10) & (df['Price'] <= 20)]
print("\nRows where Price is between 10 and 20:\n", filtered_df)

Original DataFrame:
   Item  Price
0    A      5
1    B     12
2    C     18
3    D     25
4    E     15

Rows where Price is between 10 and 20:
   Item  Price
1    B     12
2    C     18
4    E     15


87. Replace all values greater than a threshold (e.g., 100) with a fixed value (e.g., 100).
---

In [245]:
# Example DataFrame
data = {
    "Item": ["A", "B", "C", "D"],
    "Sales": [80, 120, 95, 150],
    "Profit": [50, 200, 110, 90]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Replace values greater than 100 **only in numeric columns**
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].clip(upper=100)
print("\nDataFrame after replacing values greater than 100 with 100:\n", df)

Original DataFrame:
   Item  Sales  Profit
0    A     80      50
1    B    120     200
2    C     95     110
3    D    150      90

DataFrame after replacing values greater than 100 with 100:
   Item  Sales  Profit
0    A     80      50
1    B    100     100
2    C     95     100
3    D    100      90


88. Filter rows where two or more conditions are true (e.g., Gender == 'Male' and Age > 30).
---

In [247]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 35, 28, 40, 22],
    "Gender": ["Female", "Male", "Male", "Male", "Female"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Filter rows where Gender is 'Male' AND Age > 30
filtered_df = df[(df['Gender'] == 'Male') & (df['Age'] > 30)]
print("\nRows where Gender is 'Male' and Age > 30:\n", filtered_df)

Original DataFrame:
       Name  Age  Gender
0    Alice   25  Female
1      Bob   35    Male
2  Charlie   28    Male
3    David   40    Male
4      Eve   22  Female

Rows where Gender is 'Male' and Age > 30:
     Name  Age Gender
1    Bob   35   Male
3  David   40   Male


89. Create a new column that is the result of an arithmetic operation between two existing columns.
---

In [249]:
# Example DataFrame
data = {
    "Price": [100, 150, 200, 120],
    "Quantity": [2, 3, 5, 4]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Create a new column 'Total' as Price * Quantity
df['Total'] = df['Price'] * df['Quantity']
print("\nDataFrame after adding 'Total' column:\n", df)

Original DataFrame:
    Price  Quantity
0    100         2
1    150         3
2    200         5
3    120         4

DataFrame after adding 'Total' column:
    Price  Quantity  Total
0    100         2    200
1    150         3    450
2    200         5   1000
3    120         4    480


90. Group the data by one column and calculate the average of another column.
---

In [250]:
# Example DataFrame
data = {
    "Department": ["HR", "IT", "HR", "IT", "Finance"],
    "Salary": [50000, 60000, 55000, 65000, 70000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Group by 'Department' and calculate average salary
avg_salary = df.groupby('Department')['Salary'].mean()
print("\nAverage Salary by Department:\n", avg_salary)

Original DataFrame:
   Department  Salary
0         HR   50000
1         IT   60000
2         HR   55000
3         IT   65000
4    Finance   70000

Average Salary by Department:
 Department
Finance    70000.0
HR         52500.0
IT         62500.0
Name: Salary, dtype: float64


91. Group by two columns and calculate multiple aggregation metrics (mean, max).
---

In [251]:
# Example DataFrame
data = {
    "Department": ["HR", "IT", "HR", "IT", "Finance", "HR", "IT"],
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male"],
    "Salary": [50000, 60000, 55000, 65000, 70000, 52000, 62000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Group by 'Department' and 'Gender' and calculate mean and max of 'Salary'
grouped = df.groupby(['Department', 'Gender'])['Salary'].agg(['mean', 'max'])
print("\nGrouped Data with mean and max:\n", grouped)

Original DataFrame:
   Department  Gender  Salary
0         HR    Male   50000
1         IT    Male   60000
2         HR  Female   55000
3         IT  Female   65000
4    Finance    Male   70000
5         HR  Female   52000
6         IT    Male   62000

Grouped Data with mean and max:
                       mean    max
Department Gender                
Finance    Male    70000.0  70000
HR         Female  53500.0  55000
           Male    50000.0  50000
IT         Female  65000.0  65000
           Male    61000.0  62000


92. Sort a DataFrame by two columns: one ascending, one descending.
---

In [252]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 35, 28, 40, 22],
    "Salary": [50000, 60000, 55000, 65000, 48000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Sort by 'Age' ascending and 'Salary' descending
sorted_df = df.sort_values(by=['Age', 'Salary'], ascending=[True, False])
print("\nDataFrame after sorting:\n", sorted_df)

Original DataFrame:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   35   60000
2  Charlie   28   55000
3    David   40   65000
4      Eve   22   48000

DataFrame after sorting:
       Name  Age  Salary
4      Eve   22   48000
0    Alice   25   50000
2  Charlie   28   55000
1      Bob   35   60000
3    David   40   65000


93. Reset the index of a DataFrame after dropping rows.
---

In [253]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 35, 28, 40]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Drop rows where Age > 30
df_filtered = df[df['Age'] <= 30]
print("\nDataFrame after dropping rows:\n", df_filtered)
# Reset the index
df_reset = df_filtered.reset_index(drop=True)
print("\nDataFrame after resetting index:\n", df_reset)

Original DataFrame:
       Name  Age
0    Alice   25
1      Bob   35
2  Charlie   28
3    David   40

DataFrame after dropping rows:
       Name  Age
0    Alice   25
2  Charlie   28

DataFrame after resetting index:
       Name  Age
0    Alice   25
1  Charlie   28


94. Create a pivot table showing the average salary by department and gender.
---

In [254]:
# Example DataFrame
data = {
    "Department": ["HR", "IT", "HR", "IT", "Finance", "HR", "IT"],
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male"],
    "Salary": [50000, 60000, 55000, 65000, 70000, 52000, 62000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Create pivot table
pivot = pd.pivot_table(df, values='Salary', index='Department', columns='Gender', aggfunc='mean')
print("\nPivot table (Average Salary by Department and Gender):\n", pivot)

Original DataFrame:
   Department  Gender  Salary
0         HR    Male   50000
1         IT    Male   60000
2         HR  Female   55000
3         IT  Female   65000
4    Finance    Male   70000
5         HR  Female   52000
6         IT    Male   62000

Pivot table (Average Salary by Department and Gender):
 Gender       Female     Male
Department                  
Finance         NaN  70000.0
HR          53500.0  50000.0
IT          65000.0  61000.0


95. Merge two DataFrames using a common key column.
---

In [256]:
# Example DataFrame 1
df1 = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"]
})
# Example DataFrame 2
df2 = pd.DataFrame({
    "EmployeeID": [101, 102, 104, 105],
    "Salary": [50000, 60000, 65000, 70000]
})
print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n", df2)
# Merge DataFrames on 'EmployeeID'
merged_df = pd.merge(df1, df2, on='EmployeeID', how='inner')  # 'inner' keeps only matching keys
print("\nMerged DataFrame:\n", merged_df)

DataFrame 1:
    EmployeeID     Name
0         101    Alice
1         102      Bob
2         103  Charlie
3         104    David

DataFrame 2:
    EmployeeID  Salary
0         101   50000
1         102   60000
2         104   65000
3         105   70000

Merged DataFrame:
    EmployeeID   Name  Salary
0         101  Alice   50000
1         102    Bob   60000
2         104  David   65000


96. Concatenate two DataFrames vertically and reset the index.
---

In [258]:
# Example DataFrame 1
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
})
# Example DataFrame 2
df2 = pd.DataFrame({
    "Name": ["Charlie", "David"],
    "Age": [28, 35]
})
print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n", df2)
# Concatenate vertically
df_concat = pd.concat([df1, df2], ignore_index=True)  # ignore_index=True resets the index
print("\nConcatenated DataFrame:\n", df_concat)

DataFrame 1:
     Name  Age
0  Alice   25
1    Bob   30

DataFrame 2:
       Name  Age
0  Charlie   28
1    David   35

Concatenated DataFrame:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28
3    David   35


97. Extract the year from a column containing dates.
---

In [259]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "JoiningDate": ["2021-05-15", "2020-08-22", "2019-12-10"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# Convert 'JoiningDate' to datetime format
df['JoiningDate'] = pd.to_datetime(df['JoiningDate'])
# Extract year
df['Year'] = df['JoiningDate'].dt.year
print("\nDataFrame with Year column:\n", df)

Original DataFrame:
       Name JoiningDate
0    Alice  2021-05-15
1      Bob  2020-08-22
2  Charlie  2019-12-10

DataFrame with Year column:
       Name JoiningDate  Year
0    Alice  2021-05-15  2021
1      Bob  2020-08-22  2020
2  Charlie  2019-12-10  2019


98. Count the number of unique values in a column.
---

In [260]:
# Example DataFrame
data = {
    "Department": ["HR", "IT", "HR", "Finance", "IT", "Finance", "HR"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Count number of unique values in 'Department'
num_unique = df['Department'].nunique()
print("\nNumber of unique departments:", num_unique)

Original DataFrame:
   Department
0         HR
1         IT
2         HR
3    Finance
4         IT
5    Finance
6         HR

Number of unique departments: 3


99. Convert a categorical column (e.g., "Gender") into one-hot encoded format.
---

In [261]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Gender": ["Female", "Male", "Male", "Female"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
# One-hot encode the 'Gender' column
df_encoded = pd.get_dummies(df, columns=['Gender'])
print("\nDataFrame after one-hot encoding:\n", df_encoded)

Original DataFrame:
       Name  Gender
0    Alice  Female
1      Bob    Male
2  Charlie    Male
3    David  Female

DataFrame after one-hot encoding:
       Name  Gender_Female  Gender_Male
0    Alice           True        False
1      Bob          False         True
2  Charlie          False         True
3    David           True        False


100. Apply a custom function to a column using .apply() to categorize values (e.g., Grade from Marks).
---

In [262]:
# Example DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 72, 60, 48]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Define a custom function to assign grades
def assign_grade(marks):
    if marks >= 80:
        return 'A'
    elif marks >= 70:
        return 'B'
    elif marks >= 50:
        return 'C'
    else:
        return 'F'
# Apply the function to 'Marks' column
df['Grade'] = df['Marks'].apply(assign_grade)
print("\nDataFrame with Grades:\n", df)

Original DataFrame:
       Name  Marks
0    Alice     85
1      Bob     72
2  Charlie     60
3    David     48

DataFrame with Grades:
       Name  Marks Grade
0    Alice     85     A
1      Bob     72     B
2  Charlie     60     C
3    David     48     F
